export const emailStyles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif',
    padding: '20px 0',
  },
  container: {
    backgroundColor: '#ffffff',
    border: '1px solid #dddddd',
    borderRadius: '12px',
    margin: '0 auto',
    padding: '40px 24px',
    maxWidth: '560px',
  },
  logo: {
    color: '#ff385c',
    fontSize: '24px',
    fontWeight: '700',
    margin: '0 0 24px 0',
    display: 'inline-block',
  },
  h1: {
    color: '#222222',
    fontSize: '22px',
    fontWeight: '600',
    lineHeight: '1.25',
    margin: '0 0 16px 0',
  },
  p: {
    color: '#222222',
    fontSize: '15px',
    lineHeight: '1.5',
    margin: '0 0 16px 0',
  },
  table: {
    width: '100%',
    margin: '20px 0',
    borderCollapse: 'collapse' as const,
  },
  tableCellLabel: {
    padding: '10px 12px',
    border: '1px solid #dddddd',
    backgroundColor: '#f7f7f7',
    fontWeight: '600',
    color: '#222222',
    fontSize: '14px',
    width: '40%',
  },
  tableCellValue: {
    padding: '10px 12px',
    border: '1px solid #dddddd',
    color: '#222222',
    fontSize: '14px',
  },
  button: {
    backgroundColor: '#ff385c',
    borderRadius: '8px',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: '600',
    textDecoration: 'none',
    textAlign: 'center' as const,
    display: 'block',
    padding: '14px 24px',
    marginTop: '24px',
  },
  footer: {
    color: '#6a6a6a',
    fontSize: '13px',
    lineHeight: '1.4',
    margin: '32px 0 0 0',
    borderTop: '1px solid #dddddd',
    paddingTop: '16px',
  }
};
